### PR TITLE
Create Simplified Chinese translation

### PR DESCRIPTION
**Pull request by picturepan2**
This Pull Request includes all Simplified Chinese translations in English currently. But I have some notes to reviewers: 

- "account" is translated to "帐号", but "账号" is good for money/finance related account. We should make an unified translation for it in all products.
- Ⓝ is replaced with HTML entity code `&#9411;`, which I did not change for English, for better compatibility. 
- The introduction of NEAR is different to the one in near.org. I think we should update it in Wallet too.

### CODE REVIEW

**Comment by Patrick1904** [comment]
> * "account" is translated to "帐号", but "账号" is good for money/finance related account. We should make an unified translation for it in all products.

Should we create a localization doc (notion?) and list specific terminology and corresponding translations that we can point to? cc @vgrichina

> * Ⓝ is replaced with HTML entity code `&#9411;`, which I did not change for English, for better compatibility.

Good point. I’ll replace with html entity everywhere else.

> * The introduction of NEAR is different to the one in near.org. I think we should update it in Wallet too.

Agree. Can you please post the intro we should use here and I’ll update Wallet. Did you use the near.org intro for Chinese? If not, can you please update it.

**Comment by picturepan2** [comment]
@Patrick1904 Right. Some basic terminology definitions are good for now. I also noticed NEAR Wallet and Explorer share some translations.

For the introduction of NEAR, the one in the Wallet is `NEAR is a scalable computing and storage platform that changes how the web works for better.`, but in near.org it is much longer `NEAR is a decentralized storage and compute platform that is secure enough to manage high value assets like money or identity and performant enough to make them useful for everyday people, putting the power of the Open Web in their hands.`. 

btw, the recover Email sent from the wallet is still from @nearprotocol.com? The English translation still has it.

I also have some comments in the code which I write in Chinese. Maybe @azhang2013 or other Chinese guys can help and discuss.

**Comment by Patrick1904** [comment]
> btw, the recover Email sent from the wallet is still from @nearprotocol.com? The English translation still has it.

Did you use wallet.testnet.near.org when sending the recovery email?

**Comment by picturepan2** [comment]
image
There is no Email options for me.

**Comment by azhang2013** [comment]
@picturepan2 
Please use the below for the intro of NEAR in Chinese

> NEAR是开放性网络 (Open Web) 的基础架构, 提供了一个去中心化存储和计算平台。和绝大部分现有区块链平台不同的是，NEAR力求把生涩难懂的区块链做到平易近人。通过底层的可延展性，中间层的优化，到应用层成熟的工具，为开发者和用户提供了简洁友好的使用体验。

"account" is translated to "帐号" - let's translate that into "账户” instead

**Comment by picturepan2** [comment]
@azhang2013 OK. But maybe the intro is too long for this position?
image

There are some other questions need you review. Please look at those above.

**Comment by vgrichina** [comment]
@ilblackdragon @azhang2013 
link to open on GitPod (allows to test this live): http://gitpod.io/#https://github.com/near/near-wallet/pull/582

**Comment by vgrichina** [comment]
@azhang2013 @picturepan2 
Check out https://github.com/near/near-wallet/pull/590 for live version (I recommend changing base bra ch in this PR to merge into that one).

**Comment by picturepan2** [comment]
@Patrick1904 @azhang2013 @vgrichina Hi, I've tested locally. Some more comments below:
1. Recovery Emails are from @nearprotocol.com which is ok, but Email content is in English.
2. Recovery SMS are from US number? I can't get any message on my cell phone with a Chinese number. I can imagine that SMS content is in English too.
3. The strings like `Summary, Send and Receive` in the `NavLinks.js` (and `UserLinks.js`) are not translation elements. They need to be rewritten. 
4. The 3rd party libraries like date and time (etc. 3 mins ago in the timeline) and others are English only.
5. Chinese fonts in CSS need to be improved as well. I am committing something from my expertise of [CSS framework](https://picturepan2.github.io/spectre/elements/typography.html#typography-east-asian) soon. 
6. I believe the Wallet team and Explorer team should work together to get the multilingual feature done because both of them share lots of components and strings.

**Comment by picturepan2** [comment]
@Patrick1904 3 frontend suggestions.
1. Make less cross domain CSS loading. Better to combine and compress them in production.
2. Define `font-family` in CSS, not in components, because different language will have different font rules. It is too hard to improve it when `font-family` is defined in every components.
3. Change `lang` of `<html>` when switch languages.

**Comment by picturepan2** [comment]
Any update on progress?

**Comment by Patrick1904** [comment]
@picturepan2 great suggestions. I will make those changes once I'm done with some pressing launch blocking priorities (Ledger, etc). Also, feel free to submit PR for any of them if you feel comfortable.

**Comment by vgrichina** [comment]
> Make less cross domain CSS loading. Better to combine and compress them in production.

This is going to happen as part of https://github.com/near/near-wallet/issues/620

We also have some plans to reduce bundle size, etc by removing some stuff (like semantic-ui framework), but there is more high priority stuff for now and there is plenty of work as a whole. So we are doing it bite sized.

**Comment by corwinharrell** [comment]
Screen Shot 2020-06-29 at 1 12 14 AM

Just adding this here for reference @picturepan2

**Comment by vgrichina** [comment]
@corwinharrell @picturepan2 switcher works alright for me (though looks somewhat different than on mockups). 

I think it makes sense to merge as is and then we can iterate with @Patrick1904 to improve switcher UX, etc. Basically makes sense to do further fixes in follow up PRs.

**Comment by picturepan2** [comment]
Sorry I haven’t implemented the design. But I think it is ok to merge first then UI improvement and other languages.

**Comment by Patrick1904** [comment]
@picturepan2 it looks great so far. Do you want to finish the design too? Let me know if you need any help.

**Comment by picturepan2** [comment]
@Patrick1904 Yes, the design @corwinharrell shared above? 
I forget to fix something. Such as `Simplified Chinese` -> `简体中文` which makes easier for non-English users to understand. I will do it in next PR.
BTW, I saw Russian language, do you finish translation? You can add a new language by importing it in `components/Routing.js`. There is Chinese example in the file.

**Comment by picturepan2** [comment]
@Patrick1904 For now, two features missing. 
1). Auto detect user's language and redirect. 
2). Saving user's selection in localStorage(?) no idea if it is safe enough for NEAR Wallet. Or just do feature 1)?

**Comment by Patrick1904** [comment]
> @Patrick1904 Yes, the design @corwinharrell shared above?

Yes exactly the design attached above


> BTW, I saw Russian language, do you finish translation? You can add a new language by importing it in `components/Routing.js`. There is Chinese example in the file.

@vgrichina should we offer Russian now too? Seems we'll often have an incomplete translation since we're pushing a lot of features so might not be a huge deal if it's not complete?

**Comment by Patrick1904** [comment]
> @Patrick1904 For now, two features missing.
> 1). Auto detect user's language and redirect.
> 2). Saving user's selection in localStorage(?) no idea if it is safe enough for NEAR Wallet. Or just do feature 1)?

1 and 2 would be really nice I think, but not critical to launch V0. localStorage should be fine, there's no sensitive information.

**Comment by picturepan2** [comment]
@Patrick1904 2) Done in a new branch locally.

**Pull request merged**
