### PR TITLE
Disable 2FA (pre-release version)

### PR DESCRIPTION
**Pull request by vgrichina**
Should be safe enough to use to disable 2FA to remove remaining funds from accounts.

### CODE REVIEW

**Comment by Patrick1904** [comment]
@vgrichina @mattlockyer I noticed while testing this that the "Active since XX" on `/profile` doesn't update in CH when I re-enable 2FA.
Screen Shot 2021-01-29 at 5 38 27 PM

**Comment by mattlockyer** [comment]
I think contract helper is using some default `createdAt` / `updatedAt` timestamps (not sure of the exact name) in the model.

2FA methods are stored as recoveryMethod models in CH.
https://github.com/near/near-contract-helper/blob/master/models/recovery-method.js

@vgrichina if the user is trying to re-enable, `requestId` will be -1. I think we'd have to manually update `createdAt`?

**Comment by Patrick1904** [comment]
> I think contract helper is using some default `createdAt` / `updatedAt` timestamps (not sure of the exact name) in the model.
> 
> 2FA methods are stored as recoveryMethod models in CH.
> https://github.com/near/near-contract-helper/blob/master/models/recovery-method.js
> 
> @vgrichina if the user is trying to re-enable, `requestId` will be -1. I think we'd have to manually update `createdAt`?

@mattlockyer yes I think any time user enables 2FA, we can just override current `createdAt`

**Comment by vgrichina** [comment]
I've seen the requestId = -1 thing when I try to recover 2FA account. Sometimes it won't create multisig request but send e-mail (with wrong content).

**Comment by mattlockyer** [comment]
> I've seen the `requestId = -1` thing when I try to recover 2FA account. 

Yes that is another issue unrelated to the date.

Attempted fix here: https://github.com/near/near-api-js/pull/482

If you'd like to fix the date issue in CH you would update the necessary date fields when `requestId == -1` in CH.

**Comment by Patrick1904** [comment]
@vgrichina @MaximusHaximus I think this PR may have gotten too out of sync with contract helper because I'm not able to recover any 2FA account anymore using the staging link: https://deploy-preview-1344--near-wallet-staging.netlify.app/

I just keep seeing in console: `Invalid security code. Please try again.`

**Comment by vgrichina** [comment]
> @vgrichina @MaximusHaximus I think this PR may have gotten too out of sync with contract helper because I'm not able to recover any 2FA account anymore using the staging link: https://deploy-preview-1344--near-wallet-staging.netlify.app/
> 
> I just keep seeing in console: `Invalid security code. Please try again.`

yeah, this PR needs to be rebased + use latest version of near-api-js

**Comment by MaximusHaximus** [comment]
Key rotation no longer necessary due to changes in nearcore

**Pull request closed without merging**
