### PR TITLE
New translations into Russian

### PR DESCRIPTION
**Pull request by denis-skripnik**
Translated from English into Russian what was not translated earlier.

Perhaps somewhere the context misunderstood, which is why it is incorrectly written. Please check

### CODE REVIEW

**Review by Patrick1904 — APPROVED** [review]
Thank you @denis-skripnik! 🙏

**Comment by artem-p** [comment]
My 2 cents:

- "Almost there" is rather "Почти готово" than "Почти на месте"
- also typo in "логиноном"

**Comment by artem-p** [comment]
Also, if I'm not mistake, "Застейканно" should be with one "н" letter, "Застейкано".

**Comment by denis-skripnik** [comment]
Thank you. Fixed the mistakes.

**Pull request merged**
