### PR TITLE
Show proper title if login with near-cli (#1082)

### PR DESCRIPTION
**Pull request by marcinbodnar**

### CODE REVIEW

**Comment by marcinbodnar** [comment]
@kcole16 @vgrichina 
We are not able to detect that it was in fact CLI - referrer will be empty, like when entering URL directly into the browser tab. So in this case I'm checking the title, and if the title is `NEAR CLI` it is shown. It should be secure because the referrer is checked first, so this title will appear only if the referrer is empty.

Also, we are showing `title` from URL on the details page and on the confirm account id page. So I also changed it to show the same title like on the main login page.

**Comment by vgrichina** [comment]
@marcinbodnar we cannot trust title passed through URL unfortunately, so we cannot show it to user. For NEAR CLI we should show something like "Unknown App".

We also will need to switch to using callback URL domain instead https://github.com/near/near-wallet/issues/726

**Comment by marcinbodnar** [comment]
@marcinbodnar even for this particular situation (when no referref)?

"Unknown app" is shown now, #1082

**Comment by kcole16** [comment]
@marcinbodnar My fault here. I thought we could determine whether the referrer was localhost. If this is not the case, we should keep it as-is. Otherwise, it's abusable (anyone could put "NEAR CLI" as the title, and we can't easily verify).

**Comment by marcinbodnar** [comment]
@kcole16 
> anyone could put "NEAR CLI" as the title, and we can't easily verify

It's true but only in case you copy and paste this URL into a new browser tab, or the page will be launched from the console.

But if that's also dangerous then let me remove the title and we can merge fixes for details and confirm account id page.

**Comment by vgrichina** [comment]
> It's true but only in case you copy and paste this URL into a new browser tab, or the page will be launched from the console.

@marcinbodnar not sure what do you mean. Literally everyone can construct such URL and e.g. post it in some public forum.

**Comment by marcinbodnar** [comment]
> not sure what do you mean. Literally everyone can construct such URL and e.g. post it in some public forum.

@vgrichina Yes, but if you click on this link the `referrer` will not be empty, and the title will not appear.

**Pull request merged**
