### PR TITLE
Point 'HELP' button to Zendesk page

### PR DESCRIPTION
**Pull request by Patrick1904**
Point 'HELP' button to `https://nearhelp.zendesk.com/` instead of Discord.

### CODE REVIEW

**Review by kcole16 — APPROVED** [review]

**Review by vgrichina — CHANGES_REQUESTED** [review]
@Patrick1904 we shouldn't embed code loaded from Zendesk as it's extra security risk for wallet.

I think it's best we just link to the page to get support from existing Help button.

**Comment by Patrick1904** [comment]
> @Patrick1904 we shouldn't embed code loaded from Zendesk as it's extra security risk for wallet.
> 
> I think it's best we just link to the page to get support from existing Help button.

@kcole16 are you onboard with just linking to Zendesk page using existing button?

**Comment by kcole16** [comment]
> @kcole16 are you onboard with just linking to Zendesk page using existing button?

I'm onboard. It's not ideal, but security is #1 priority always (I should've thought of that when writing the issue).

**Comment by Patrick1904** [comment]
> @Patrick1904 we shouldn't embed code loaded from Zendesk as it's extra security risk for wallet.
> 
> I think it's best we just link to the page to get support from existing Help button.

The current 'HELP' button only exists on desktop. For mobile users, the 'join community' link in the footer is the only option to get help, and it leads to Discord, not Zendesk.

I suggest we add the 'HELP' button to the mobile nav too then.

@kcole16 @corwinharrell @vgrichina

**Pull request merged**
