### PR TITLE
Add functionCall args to /sign detail page (#1175)

### PR DESCRIPTION
**Pull request by marcinbodnar**

### CODE REVIEW

**Comment by kcole16** [comment]
@marcinbodnar Noticed this when testing with berryclub.io on the staging link:
Screen Shot 2020-12-07 at 12 49 40 PM

**Comment by marcinbodnar** [comment]
@kcole16 check now please.

**Review by kcole16 — APPROVED** [review]

**Comment by kcole16** [comment]
@marcinbodnar Looks good!

**Review by vgrichina — CHANGES_REQUESTED** [review]
@marcinbodnar looks good overall, but need to be prepared to handle non-JSON args. Can fail JSON parsing – makes sense to assume it's arbitrary binary then. Can use something like https://github.com/bma73/hexdump-js for binary, or just show a warning about binary args for now.

**Comment by marcinbodnar** [comment]
@vgrichina got it, do we have any FunctionCall with binary args to test?

**Comment by marcinbodnar** [comment]
@vgrichina this will work?

**Comment by vgrichina** [comment]
> @vgrichina this will work?

I don't think this will work, I think `args` is always binary before you parse it from JSON, so basically you have to handle error when parsing

I think @chadoh should have an example sending binary args with bridge. Is there anything live we can use for testing wallet?

**Comment by vgrichina** [comment]
@marcinbodnar try https://gitpod.io/#snapshot/8f156a4b-9376-41f7-995e-27a79e23b9a5 – it should do non-JSON method call. You need to attach some tokens as donation to get redirect to wallet.

**Comment by marcinbodnar** [comment]
@vgrichina now it should work fine

**Review by vgrichina — APPROVED** [review]

**Pull request merged**
