### PR TITLE
Enable users to claim linkdrops to existing or new account

### PR DESCRIPTION
**Pull request by Patrick1904**
Changes:
1. Add linkdrop landing page (`/linkdrop/contract/key`)
2. Enable claiming linkdrop to existing or new account
3. Enable user to recover account with seed phrase or Ledger before claiming linkdrop
4. Redirect linkdrop URLs from `/create/contract/key` --> `/linkdrop/contract/key` **unless** URL param includes `redirect=false`

For testing, create linkdrops here: https://near-drop-testnet.onrender.com/ 

Screen Shot 2021-04-26 at 3 09 44 PM

### CODE REVIEW

**Review by vgrichina — APPROVED** [review]
LGTM. 

I think there was a minor issue that when creating account I got both a new popup about Linkdrop and a "Success" notification, but it shouldn't be a blocker.

**Review by ihaid — APPROVED** [review]

**Comment by corwinharrell** [comment]
@Patrick1904 following the link drop link takes me to /create. How do I get to the new link drop page?

**Comment by Patrick1904** [comment]
> @Patrick1904 following the link drop link takes me to /create. How do I get to the new link drop page?

@corwinharrell sorry forgot to mention that you need to replace the linkdrop URL with https://near-wallet-pr-1547.onrender.com/ so that you're pointing towards this PR.

**Comment by Patrick1904** [comment]
> LGTM.
> 
> I think there was a minor issue that when creating account I got both a new popup about Linkdrop and a "Success" notification, but it shouldn't be a blocker.

@vgrichina thanks for catching. I fixed it here: https://github.com/near/near-wallet/pull/1547/commits/7702b74590d740ab0d81bf6aa8220f0d2239bcdd

**Review by corwinharrell — APPROVED** [review]
LGTM 🚀

**Pull request merged**
