### PR TITLE
Prototype loading fungible tokens

### PR DESCRIPTION
**Pull request by vgrichina**
This is just rough prototype with hardcoded contract list to show how it might look with real data.

(farm token not yet conforming to standard so failing)

Screenshot 2021-03-03 at 01 39 22

### CODE REVIEW

**Comment by corwinharrell** [comment]
@vgrichina do you see anything wrong with just using the symbol (eg `wNEAR`) for the primary name in the list for now? (vs the long string?

It seems like if we are pulling contract data, and the "name" as displayed above is functioning more like a description which could potentially be a super long string, we may just want to use the shorter "symbol" alternative.

**Comment by vgrichina** [comment]
> @vgrichina do you see anything wrong with just using the symbol (eg `wNEAR`) for the primary name in the list for now? (vs the long string?
> 
> It seems like if we are pulling contract data, and the "name" as displayed above is functioning more like a description which could potentially be a super long string, we may just want to use the shorter "symbol" alternative.

yeah, this should work

so then we just need to have placeholder icon as well

**Comment by vgrichina** [comment]
@corwinharrell I've changed according to your suggestion, now just need placeholder icon to use

**Comment by corwinharrell** [comment]
@vgrichina in the future, what might be used to display icons if not `token.symbol`? Is it up to the author to add something like `token.icon` or is it on us to request that they include that? Seems like it would make sense for these contracts to have the following endpoints:

```
name: 'Banana',
abbreviation: 'BNNA'
icon: '🍌',
contract: 'berryclub.ek.near',
balance: '500'
```

How much influence do we have over what contract authors include and how it is structured?

**Comment by vgrichina** [comment]
> @vgrichina in the future, what might be used to display icons if not `token.symbol`? Is it up to the author to add something like `token.icon` or is it on us to request that they include that? Seems like it would make sense for these contracts to have the following endpoints:
> 
> ```
> name: 'Banana',
> abbreviation: 'BNNA'
> icon: '🍌',
> contract: 'berryclub.ek.near',
> balance: '500'
> ```
> 
> How much influence do we have over what contract authors include and how it is structured?

We recommend to include icon as a data URL with SVG of the icon. But it’s gonna be optional.

**Comment by vgrichina** [comment]
> > @vgrichina in the future, what might be used to display icons if not `token.symbol`? Is it up to the author to add something like `token.icon` or is it on us to request that they include that? Seems like it would make sense for these contracts to have the following endpoints:
> > ```
> > name: 'Banana',
> > abbreviation: 'BNNA'
> > icon: '🍌',
> > contract: 'berryclub.ek.near',
> > balance: '500'
> > ```
> > 
> > 
> > How much influence do we have over what contract authors include and how it is structured?
> 
> We recommend to include icon as a data URL with SVG of the icon. But it’s gonna be optional.

Actually this got me thinking that we need to make some template so that icons are reasonable. @corwinharrell may you help with that so that @chadoh can include it in standard?

**Comment by djsatok** [comment]
How the wallet will keep track of the tokens that should be displayed? Is there an ability to add a custom token?
I suggest to store in the wallet the top 20 bridge ERC-20s, so they get automatically pulled in the UI, in case a user owns any of them. This automation will save the user time to find an account for bridged token, and manually enter it somewhere in the wallet.
cc @jimmy3dita @corwinharrell

**Comment by jimmy3dita** [comment]
> How the wallet will keep track of the tokens that should be displayed? Is there an ability to add a custom token?
> I suggest to store in the wallet the top 20 bridge ERC-20s, so they get automatically pulled in the UI, in case a user owns any of them. This automation will save the user time to find an account for bridged token, and manually enter it somewhere in the wallet.
> cc @jimmy3dita @corwinharrell

I second this one, as mentioned in today's meeting. Do you have the list handy, to copy/paste it here already?

**Comment by vgrichina** [comment]
> How the wallet will keep track of the tokens that should be displayed? Is there an ability to add a custom token?
> I suggest to store in the wallet the top 20 bridge ERC-20s, so they get automatically pulled in the UI, in case a user owns any of them. This automation will save the user time to find an account for bridged token, and manually enter it somewhere in the wallet.
> cc @jimmy3dita @corwinharrell

Mid term plan is to query contract helper which queries indexer DB:
https://github.com/near/near-contract-helper/pull/322 cc @jimmy3dita 

Might keep list hardcoded for v0 if needed to void blocking, but definitely no plan to make user manage them manually. Maybe later on we’d need to add separate “inbox” for airdrops however.

**Comment by corwinharrell** [comment]
@vgrichina regardless of where we get to with the [discussion on token icons](https://github.com/near/near-wallet/discussions/1530), we'll be using the following icon as a placeholder for NEP141 token contracts that do not provide one. Feel free to throw this into the UI as a default:

[fungible-token-placeholder.svg.zip](https://github.com/near/near-wallet/files/6116939/fungible-token-placeholder.svg.zip)

**Comment by Patrick1904** [comment]
@corwinharrell @vgrichina I added the 'default' token icon, please see below. However, how do we know when to use a provided `symbol` vs the current default? Considering `symbol` could be either a string (**BANANA** or **wNEAR**), or generally supported icons  (🥑)?

Seems we might have to maintain a list (with icons) on our end if we want to maintain consistency and quality?

Screen Shot 2021-03-10 at 2 28 57 PM

**Comment by corwinharrell** [comment]
> @corwinharrell @vgrichina I added the 'default' token icon, please see below. However, how do we know when to use a provided `symbol` vs the current default? Considering `symbol` could be either a string (**BANANA** or **wNEAR**), or generally supported icons (🥑)?
> 
> Seems we might have to maintain a list (with icons) on our end if we want to maintain consistency and quality?
> 
> Screen Shot 2021-03-10 at 2 28 57 PM

@Patrick1904 see https://github.com/near/near-wallet/discussions/1530

I believe token contracts will now have an option for a "Symbol" (abbreviation) and an "Icon".

**Comment by corwinharrell** [comment]
@vgrichina What is the middle token in the prototype? If no symbol/name is provided, do you have any ideas on what we should display in order to identify it?

**Comment by Patrick1904** [comment]
> @Patrick1904 see #1530
> 
> I believe token contracts will now have an option for a "Symbol" (abbreviation) and an "Icon".

I see, yea it would work for some generally supported icons like 🥑.

**Comment by Patrick1904** [comment]
> @Patrick1904 see #1530
> 
> I believe token contracts will now have an option for a "Symbol" (abbreviation) and an "Icon".

@corwinharrell I see, that should work. I'll update so that we use `icon` if provided and otherwise use the default fallback icon

**Comment by vgrichina** [comment]
> @vgrichina What is the middle token in the prototype? If no symbol/name is provided, do you have any ideas on what we should display in order to identify it?

it is berry farm token (cucumber) incompatible with latest standard

that's actually a pretty good question – what should be do with tokens that we couldn't load. I assume best probably just to hide them? Or maybe only show on successful load.

**Comment by jimmy3dita** [comment]
> it is berry farm token (cucumber) incompatible with latest standard
> 
> that's actually a pretty important question – what should be do with tokens that we couldn't load. I assume best probably just to hide them? Or maybe only show on successful load.

We risk having users contacting our support team if they have some of their tokens disappear. What about showing an error instead of the amount? This would redirect them to the token creators, asking why they don't update the standard.
Alternatively, give the option to do a pull request on a very specific Json file, such that they can override the parameters we parse from the contract?

**Comment by vgrichina** [comment]
> We risk having users contacting our support team if they have some of their tokens disappear. What about showing an error instead of the amount? This would redirect them to the token creators, asking why they don't update the standard.
> Alternatively, give the option to do a pull request on a very specific Json file, such that they can override the parameters we parse from the contract?

ultimately there is going to be hundreds of different contracts that user interacted with, but only some of them would implement token standard

so I'm leaning towards just showing only once successfully loaded I guess. For next iteration can cache the successful one in local storage so that UI is less glitchy

**Comment by corwinharrell** [comment]
@vgrichina @Patrick1904 cool I'm in favor of omitting contracts that don't implement the token standard.

**Comment by jimmy3dita** [comment]
> ultimately there is going to be hundreds of different contracts that user interacted with, but only some of them would implement token standard
> 
> so I'm leaning towards just showing only once successfully loaded I guess. For next iteration can cache the successful one in local storage so that UI is less glitchy

I try to formulate again my answer:
- I'm good with not listing tokens that don't follow the standards and can't be loaded properly
- I'm worried if we disable tokens mid-flight, after the user has seen them in the wallet and used them

The former is totally good and makes 100% sense, and it is good if it can also prevent the latter.

**Comment by djsatok** [comment]
> I second this one, as mentioned in today's meeting. Do you have the list handy, to copy/paste it here already?
Will post it here once it's ready

**Comment by djsatok** [comment]
```
{
  "erc20": [
    { "name": "USDT",  "address": "0xdac17f958d2ee523a2206206994597c13d831ec7" },
    { "name": "UNI",   "address": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984" },
    { "name": "LINK",  "address": "0x514910771af9ca656af840dff83e8264ecf986ca" },
    { "name": "USDC",  "address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" },
    { "name": "WBTC",  "address": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599" },
    { "name": "AAVE",  "address": "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9" },
    { "name": "CRO",   "address": "0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b" },
    { "name": "FTT",   "address": "0x50d1c9771902476076ecfc8b2a83ad6b9355a4c9" },
    { "name": "CHZ",   "address": "0x3506424f91fd33084466f402d5d97f05f8e3b4af" },
    { "name": "BUSD",  "address": "0x4Fabb145d64652a948d72533023f6E7A623C7C53" },
    { "name": "HT",    "address": "0x6f259637dcd74c767781e37bc6133cd6a68aa161" },
    { "name": "DAI",   "address": "0x6b175474e89094c44da98b954eedeac495271d0f" },
    { "name": "SUSHI", "address": "0x6b3595068778dd592e39a122f4f5a5cf09c90fe2" },
    { "name": "SNX",   "address": "0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f" },
    { "name": "GRT",   "address": "0xc944e90c64b2c07662a292be6244bdf05cda44a7" },
    { "name": "MKR",   "address": "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2" },
    { "name": "COMP",  "address": "0xc00e94cb662c3520282e6f5717214004a7f26888" },
    { "name": "LEO",   "address": "0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3" },
    { "name": "MATIC", "address": "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0" },
    { "name": "ENJ",   "address": "0xf629cbd94d3791c9250152bd8dfbdf380e2a3b9c" }
  ]
}
```

**Comment by vgrichina** [comment]
@djsatok we are building a wallet for NEAR though, so need to know corresponding contract names on NEAR :-P

In any case I propose on Monday we just launch this with hardcoded list of tokens that work for sure (wrapped NEAR, bananas, whatever else get bridged initially from ETH) as https://github.com/near/near-wallet/pull/1377 release gonna already be pretty complicated logistically.

**Comment by djsatok** [comment]
@vgrichina updated the list above (something out, something in)
The naming of the bridged tokens was fixed by @corwinharrell already. Just add `n` in the end. So bridged `DAI` should be referred to as `DAIn`.

**Comment by corwinharrell** [comment]
> @vgrichina updated the list above (something out, something in)
> The naming of the bridged tokens was fixed by @corwinharrell already. Just add `n` in the end. So bridged `DAI` should be referred to as `DAIn`.

I believe it's actually the other way around. @chadoh can you confirm and perhaps lay out the naming system that we landed on somewhere as a reference with examples?

**Comment by djsatok** [comment]
> > @vgrichina updated the list above (something out, something in)
> > The naming of the bridged tokens was fixed by @corwinharrell already. Just add `n` in the end. So bridged `DAI` should be referred to as `DAIn`.
> 
> I believe it's actually the other way around. @chadoh can you confirm and perhaps lay out the naming system that we landed on somewhere as a reference with examples?

I also like `nDAI` more, if it counts. `DAIn` is used in the FE at the moment, but we can update it.

**Comment by chadoh** [comment]
Here's the full results from the polls during [my ETHDenver talk](https://youtu.be/JVUy9LXzwoE): [poll results.pdf](https://github.com/near/near-wallet/files/6145114/Chad.s.ETHDenver.talk.s.poll.results.pdf)

Relevant poll:

10 of 14 respondees want nDAI

As you can see, 10 of 14 respondees wanted nDAI or nDAI<sup>21</sup>.

(The first poll here also had a fairly strong signal from the participants. Most people feel ok about using the phrase "bridged NEP141" to describe "tokens which are _currently_ NEP141s on NEAR but which started their lives as ERC20s on Ethereum.")

**Comment by chadoh** [comment]
> @djsatok we are building a wallet for NEAR though, so need to know corresponding contract names on NEAR :-P

I think @vgrichina may have been asking for NEAR contract addresses here, since only Ethereum contract addresses were given.

**Comment by jimmy3dita** [comment]
I did a run on Testnet at the link https://near-wallet-pr-1512.onrender.com/ and it's not showing balances. Hope it helps

Schermata 2021-03-16 alle 13 34 56

**Comment by vgrichina** [comment]
> I did a run on Testnet at the link https://near-wallet-pr-1512.onrender.com/ and it's not showing balances. On mainnet it works normally. Hope it helps
> 
> Schermata 2021-03-16 alle 13 34 56

it cannot work on testnet because there are no corresponding token contracts on testnet

**Comment by djsatok** [comment]
@vgrichina in order to get any ERC20 token address, one can call the view method of the connector contract (factory.bridge.near): `get_bridge_token_account_id`. It consumes the ERC20 address without `0x`.

At the moment corresponding accounts are deployed using the following pattern: `<ERC20address>.factory.bridge.near`, but this can potentially change, so there's a view call.

For example, `nDAI` AccountId is: [`6b175474e89094c44da98b954eedeac495271d0f.factory.bridge.near`](https://explorer.near.org/accounts/6b175474e89094c44da98b954eedeac495271d0f.factory.bridge.near)

**Comment by zavodil** [comment]
>     { "name": "COMP",  "address": "0xc00e94cb662c3520282e6f5717214004a7f26888" },
>     { "name": "YFI",   "address": "0xc00e94cb662c3520282e6f5717214004a7f26888" },

Please fix YFI address here. Correct one is 0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e regarding https://tokenlists.org/token-list?url=defi.cmc.eth

**Pull request merged**
