### PR TITLE
Release 2020-11-30

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by vgrichina** [comment]
@mattlockyer please resolve conflicts in https://github.com/near/near-wallet/pull/1171 and I'll merge after testing

**Comment by marcinbodnar** [comment]
@vgrichina we should also add this one #1237 after review.

**Review by ihaid — APPROVED** [review]

**Comment by vgrichina** [comment]
@ihaid may you do another pass as there were few small fixes

**Comment by marcinbodnar** [comment]
@vgrichina maybe we want to add this one as well #1257 - small change.

**Review by ihaid — APPROVED** [review]

**Review by mattlockyer — APPROVED** [review]

**Review by marcinbodnar — APPROVED** [review]

**Review by Patrick1904 — APPROVED** [review]

**Pull request merged**
