### PR TITLE
Login with QR code

### PR DESCRIPTION
**Pull request by Patrick1904**
Closes near/near-wallet-roadmap/issues/16
***Work in progress***

How to login on your phone w/ the help of your computer (Safari only on iOS):

1. On your computer: Go to https://near-wallet-pr-528.onrender.com/ and create an account.
Or… if you have an account and recovery link already, recover your account but change the domain to above.

2. Once you’re logged in on your computer, go to your profile and click ‘Login on another device’ to generate QR code (creates + adds key)

3. Now use your phone and go to https://near-wallet-pr-528.onrender.com/. Click ‘Use logged in device’. Or... Just open your phones camera app.

4. Scan the QR code shown on your computer

<a href="https://gitpod.io/#https://github.com/nearprotocol/near-wallet/pull/528"></a>

### CODE REVIEW

**Comment by Patrick1904** [comment]
@kcole16 do you think it’s a good idea to launch this feature? If @corwinharrell can provide a quick touch up on design I can get it ready this weekend.

**Comment by corwinharrell** [comment]
What is the most recent render url for this? Not able to preview using the links provided (testnet)

**Comment by Patrick1904** [comment]
> What is the most recent render url for this? Not able to preview using the links provided (testnet)

@corwinharrell it seems that this PR is too outdated to work anymore. Felt quite nostalgic seeing the UI when I tried recovering an account :)

I'll get it into functional state when I'm done with [fiat conversion](https://github.com/near/near-wallet/issues/1854) (targeting EOD tomorrow).

**Comment by Patrick1904** [comment]
Closing as this feature is being implemented in a different way here: https://github.com/near/near-wallet/pull/2017

**Pull request closed without merging**
