### PR TITLE
TMP: 2FA robustness improvements

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by vgrichina** [comment]
@ihaid @jimmy3dita this is supposed to speed up 2FA a bit + make more robust. Main changes are in near-api-js:
https://github.com/near/near-api-js/pull/572

we need to check that everything related to 2FA still works:
- enable/disable
- sending money and other actions in wallet
- using apps with wallet (both login and signing transactions)

**Comment by jimmy3dita** [comment]
used `a_test.testnet` to move funds back and forth, enabling and disabling 2FA multiple times.
looks good to me

**Review by jimmy3dita — APPROVED** [review]

**Review by ihaid — APPROVED** [review]

**Comment by ihaid** [comment]
LGTM

**Comment by agileurbanite** [comment]
Closing out this draft as it's not relevant atm.

**Pull request closed without merging**
