### PR TITLE
feat: pass in state_cleanup contract

### PR DESCRIPTION
**Pull request by esaminu**
This PR 

- Upgrades `near-api-js` to latest (0.45.1)
- passes in the [state_cleanup](https://github.com/near/core-contracts/blob/master/state-cleanup/res/state_cleanup.wasm) contract to integrate changes to the 2fa disable interface in near/near-api-js#823

### CODE REVIEW

**Comment by andy-haynes** [comment]
@esaminu is this still blocked? If so can you please leave a comment on what's blocking it?

**Comment by esaminu** [comment]
@andy-haynes unblocked now with `near-api-js` publish please test 2fa disable. @gutsyphilip for anything related to your `near-api-js` upgrade.

**Comment by gutsyphilip** [comment]
> @andy-haynes unblocked now with `near-api-js` publish please test 2fa disable. @gutsyphilip for anything related to your `near-api-js` upgrade.

Looks good to me! Not sure this affects the updates I made.

**Review by gutsyphilip — APPROVED** [review]

**Review by judith-Near — APPROVED** [review]
tested, lgtm!

**Pull request merged**
