### PR TITLE
Enable Disable 2FA

### PR DESCRIPTION
**Pull request by vgrichina**
Do simplest possible change to enable 2FA (without key rotation as in https://github.com/near/near-wallet/pull/1344)

Key rotation should be unnecessary given nearcore changes around the issue.

Fixes https://github.com/near/near-wallet/issues/1086

### CODE REVIEW

**Comment by jimmy3dita** [comment]
Following. Is it related to #1086 ? I'm trying to map PRs and Issues

**Comment by vgrichina** [comment]
> Following. Is it related to #1086 ? I'm trying to map PRs and Issues

Thanks, added link to description!

**Comment by vgrichina** [comment]
@jimmy3dita looks like disabling 2FA works now, but looks like an error somehow, gonna debug it

**Review by ihaid — APPROVED** [review]

**Review by Patrick1904 — APPROVED** [review]

**Comment by jimmy3dita** [comment]
I tested it and I didn't see any errors. 
However, I think we can improve the 2FA message, specifying that we are disabling this feature.

@MaximusHaximus do you have a way to detect this specific action from the contract helper? Currently, the email subject says `Confirm Transaction WARNING - Adding FULL ACCESS KEY to Account: %account%`, while it might specify something in the domain of `Confirm Transaction WARNING - REMOVING 2FA from Account: %account%`.
The email copy should change too (just a few words), so I need an idea of the needed effort.

**Pull request merged**
