### PR TITLE
Allow to pass metadata with transaction to sign

### PR DESCRIPTION
**Pull request by vgrichina**
Needs this 2 PRs to work:
https://github.com/near/near-contract-helper/pull/347
https://github.com/near/near-api-js/pull/529

### CODE REVIEW

**Comment by vgrichina** [comment]
Looks like this almost works besides:

>         const transactionHashes = await dispatch(signAndSendTransactions(transactions, accountId))

`transactionHashes` need to be propagated upstream from `signAndSendTransactions`

"Close" button on success screen shouldn't call `handleDeny`?

**Comment by jimmy3dita** [comment]
From product meeting: this is a blocker for the bridge launch, needed in the next release.

**Comment by abacabadabacaba** [comment]
A couple of remarks:

1. As I understand, the only purpose of `meta` parameter is to pass some data to the callback URL. In this case, the name is confusing. I would suggest to call it `state`, which is the name used for a parameter with a similar function in widely used [OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-4.1.1) and [OpenID Connect](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) protocols.
  Also, any app not using this parameter may be vulnerable to CSRF. What if a malicious website redirects the user to the app's callback URL?
2. To improve security, I would pass the parameters (both to and from the wallet) in `location.hash` rather than `location.search`. There are two reasons for this. The first is that it is better to avoid sending potentially sensitive values to the server, where they may be logged. The second reason is to reduce the chance of leaking the values in [`Referer` header](https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns).

**Comment by vgrichina** [comment]
@abacabadabacaba moved into separate issue:
https://github.com/near/near-wallet/issues/1546

neither of these are security regressions so not going to change for Monday release

**Pull request merged**
