### PR TITLE
Fixes for signing transactions (#566)

### PR DESCRIPTION
**Pull request by marcinbodnar**

### CODE REVIEW

**Comment by vgrichina** [comment]
@marcinbodnar we cannot be trusting `title` passed by the caller (they can pass anything to scam user), that's why we need to show Referrer domain instead.

**Comment by marcinbodnar** [comment]
@vgrichina got it. It's not using title. Want to merge it?

**Comment by vgrichina** [comment]
@marcinbodnar  may you resolve conflicts?

**Comment by marcinbodnar** [comment]
@vgrichina Done.

**Pull request merged**
