### PR TITLE
Add sign message functionality

### PR DESCRIPTION
**Pull request by H34D**
enable signing messages instead of transactions and return a signature in base64 in the callbackUrl

### CODE REVIEW

**Comment by stefanopepe** [comment]
@H34D Sebastian, this is a great contribution that we missed mostly because it's not paired with an issue introducing the user story and the acceptance criteria.

Would you be available to open one? I'll make sure that as soon as we have it, we'll provide feedback

**Comment by H34D** [comment]
> 

sure, i will do that

**Comment by H34D** [comment]
> @H34D Sebastian, this is a great contribution that we missed mostly because it's not paired with an issue introducing the user story and the acceptance criteria.
> 
> Would you be available to open one? I'll make sure that as soon as we have it, we'll provide feedback

sure, i will do that

**Comment by H34D** [comment]
Done #2435

**Pull request closed without merging**
