### PR TITLE
Add ToS modal to /create

### PR DESCRIPTION
**Pull request by Patrick1904**

### CODE REVIEW

**Review by corwinharrell — APPROVED** [review]

**Comment by corwinharrell** [comment]
LGTM. @jimmy3dita Perhaps you can come up with a better paragraph of copy for modal itself? Not sure if there's a template we can follow or something. I can look as well.

**Comment by Patrick1904** [comment]
@jimmy3dita should we change the ToS and Privacy Policy links in the footer too? If so, should both links go to the same PDF?

Screen Shot 2021-04-13 at 1 14 31 PM

**Comment by vgrichina** [comment]
@corwinharrell let's merge as is and @jimmy3dita can update copy later if needed

**Comment by Patrick1904** [comment]
@picturepan2 can you please add translations for this when you have a chance.

**Pull request merged**
