### PR TITLE
Creating an account in multiple windows open

### PR DESCRIPTION
**Pull request by marcinbodnar**

### CODE REVIEW

**Comment by vgrichina** [comment]
@marcinbodnar something I wonder is whether we need to maintain this separate list at all.

https://github.com/near/near-api-js/blob/6d4e688c0715b5257e45c4be24d39c98d5631648/src/key_stores/browser_local_storage_key_store.ts#L80

**Comment by vgrichina** [comment]
@marcinbodnar something I wonder about whether we need to maintain this list at all.

We can use `getAccounts` in key store to get full list off accounts with keys https://github.com/near/near-api-js/blob/6d4e688c0715b5257e45c4be24d39c98d5631648/src/key_stores/browser_local_storage_key_store.ts#L80

I guess it might have some false positives we'd need to filter out based on whether account still exists on chain.

**Comment by MaximusHaximus** [comment]
@marcinbodnar Is this PR still relevant, or should we close it?

**Comment by marcinbodnar** [comment]
@MaximusHaximus I'm not sure how this part of creating an account is working now, but creating an account in multiple windows should be handled anyway - I would suggest closing this PR, but create a new issue with a link to this PR - so the old solution will be visible.

**Comment by MaximusHaximus** [comment]
> @MaximusHaximus I'm not sure how this part of creating an account is working now, but creating an account in multiple windows should be handled anyway - I would suggest closing this PR, but create a new issue with a link to this PR - so the old solution will be visible.

Rather than create a new issue for the same problem, can you take a look at this and see if the code is still relevant (there are no conflicts) and still solves the problem?  It looks like this would fix https://github.com/near/near-wallet/issues/1471 which is a P1 issue that also appears to be a well written issue with reproduction case documented; I don't see any benefit in re-creating that issue :).

It looks like what we have here is a minimal impact one-line change.  If this code change still solves the problem that it was supposed to solve and hasn't introduced a negative impact, then I'd like for us to go ahead and get it merged rather than kick this particular can farther down the road with a new issue :). We just need to be sure there isn't a _negative_ consequence from this change, which should be confirmed with basic testing cases that call `saveAccount()` you do, and that the problem is still solved with this one-line change (also easily verifiable via the same reproduction case outlined in #1471).  If we're not confident that this fixes the problem and is safe, then we should close the PR and do whatever we need to to gain that confidence -- but I'm assuming this is ready to go given it's up for review.

Let's get this over the line so that users can benefit from the fix! If you discover that it either (a) doesn't fix the problem or (b) has a negative side-effect, then lets close this PR and triage the issue into a different sprint based on its priority back into _In Development_ -- but right now, this is a ghost in the system, "done", but not _really_ done until it's merged, and not being tracked in our current sprints.

**Comment by MaximusHaximus** [comment]
@marcinbodnar a friendly reminder about this PR

**Comment by marcinbodnar** [comment]
> > @MaximusHaximus I'm not sure how this part of creating an account is working now, but creating an account in multiple windows should be handled anyway - I would suggest closing this PR, but create a new issue with a link to this PR - so the old solution will be visible.
> 
> Rather than create a new issue for the same problem, can you take a look at this and see if the code is still relevant (there are no conflicts) and still solves the problem? It looks like this would fix #1471 which is a P1 issue that also appears to be a well written issue with reproduction case documented; I don't see any benefit in re-creating that issue :).
> 
> It looks like what we have here is a minimal impact one-line change. If this code change still solves the problem that it was supposed to solve and hasn't introduced a negative impact, then I'd like for us to go ahead and get it merged rather than kick this particular can farther down the road with a new issue :). We just need to be sure there isn't a _negative_ consequence from this change, which should be confirmed with basic testing cases that call `saveAccount()` you do, and that the problem is still solved with this one-line change (also easily verifiable via the same reproduction case outlined in #1471). If we're not confident that this fixes the problem and is safe, then we should close the PR and do whatever we need to to gain that confidence -- but I'm assuming this is ready to go given it's up for review.
> 
> Let's get this over the line so that users can benefit from the fix! If you discover that it either (a) doesn't fix the problem or (b) has a negative side-effect, then lets close this PR and triage the issue into a different sprint based on its priority back into _In Development_ -- but right now, this is a ghost in the system, "done", but not _really_ done until it's merged, and not being tracked in our current sprints.

I meant new PR.

**Comment by marcinbodnar** [comment]
@MaximusHaximus Done.

**Comment by MaximusHaximus** [comment]
@ihaid Can you give this a test before we merge it to testnet/staging?

**Comment by ihaid** [comment]
> @ihaid Can you give this a test before we merge it to testnet/staging?

looks go to me!

**Review by ihaid — APPROVED** [review]

**Comment by MaximusHaximus** [comment]
<3 rock and roll!

**Pull request merged**
