### PR TITLE
Mynw 62 fixes for rebased branch

### PR DESCRIPTION
**Pull request by loosefer**
Fix [comment](https://github.com/near/near-wallet/pull/2771#issuecomment-1165827796) from closed PR for [branch](https://github.com/near/near-wallet/pull/2780) with Transfer Accounts functionalities

### CODE REVIEW

**Review by gutsyphilip — APPROVED** [review]
This looks great @loosefer 
Please always remember to add descriptions and screenshots(where necessary) to your PR description. Helps provide context to anyone looking at it.

**Comment by loosefer** [comment]
@esaminu Done!

**Comment by agileurbanite** [comment]
how is this different from #2780 ?  cc @esaminu

**Comment by esaminu** [comment]
Thanks @loosefer! I merged them please review #2780 and resolve any relevant feedback by sending PRs to #2780 . @gutsyphilip please do the same

**Pull request merged**
