### PR TITLE
Handle non existing account for Sign in with Ledger (#1330)

### PR DESCRIPTION
**Pull request by marcinbodnar**

### CODE REVIEW

**Review by kcole16 — APPROVED** [review]

**Comment by vgrichina** [comment]
@marcinbodnar looks like similar issue exists for seed phrase recovery as well, reproduced when working on:
https://github.com/near/near-wallet/pull/1340

I think the solution to both is to update near-contract-helper indexer query to exclude removed keys, though I guess I need to double check what happens with keys which are added back.

**Comment by marcinbodnar** [comment]
@vgrichina 
> I think the solution to both is to update near-contract-helper indexer query to exclude removed keys

For sure, the best idea if it's technically possible.

I'm not able to reproduce it for Seed Phrase.

**Comment by vgrichina** [comment]
> I'm not able to reproduce it for Seed Phrase.

do you mean that when you delete accounts they aren't picked up for seed phrase recovery anymore?

**Comment by marcinbodnar** [comment]
@vgrichina I tried scenario like for ledger, when you claim account (implicit is deleted) and implicit account still appears in CH

**Comment by vgrichina** [comment]
> @vgrichina I tried scenario like for ledger, when you claim account (implicit is deleted) and implicit account still appears in CH

I see, in my test I was deleting original account explicitly and then reusing same seed phrase for different accounts

Looks like we have to merge this for mitigation right now anyway and when I'm 100% sure about new indexer for explorer
we have a fix here:
https://github.com/near/near-contract-helper/pull/304

**Pull request merged**
