### PR TITLE
Add more gas to linkdrop call

### PR DESCRIPTION
**Pull request by ilblackdragon**
Fixes an issue with not enough gas attached: https://explorer.near.org/transactions/2BUbseT5tzG56kNhzHumQFaPTKc4PfdHGC2TuobGgFBC

### CODE REVIEW

**Comment by kcole16** [comment]
@vgrichina Can we merge this as a hot fix to ‘stable’ as well?

**Comment by vgrichina** [comment]
@kcole16 @bowenwang1996 @mattlockyer  we need to understand why this fix works, near drops work ok on testnet without any change.

**Comment by vgrichina** [comment]
I'm cherry-picking it into `stable` branch so that mainnet wallet is fixed, but we still need to understand issue better before merging into `master`

**Comment by vgrichina** [comment]
Implemented with a way to override in config here:
https://github.com/near/near-wallet/commit/70542cb221384d9d8d8f9c37087a559a54937aea

**Pull request closed without merging**
