### PR TITLE
Add Turkish language choice to Near Wallet

### PR DESCRIPTION
**Pull request by marcinbodnar**

### CODE REVIEW

**Comment by picturepan2** [comment]
@marcinbodnar The contents are not in Turkish yet?

**Comment by marcinbodnar** [comment]
> @marcinbodnar The contents are not in Turkish yet?

For now, It's just an option in the language menu. It's waiting for a translation.

**Comment by KriptoRaptor** [comment]
> @marcinbodnar The contents are not in Turkish yet?

we're preparing the commit now :)

**Comment by marcinbodnar** [comment]
@KriptoRaptor 
testnet:
https://near-wallet-pr-2319.onrender.com/
mainnet:
https://deploy-preview-2319--near-wallet-staging.netlify.app/

**Comment by Patrick1904** [comment]
@marcinbodnar this is sweet! Do you think we could rebase this PR? It's still running the legacy onboarding flow so not able to test it properly.

**Comment by marcinbodnar** [comment]
@Patrick1904
Done. There will be some translations missing, but I think the best would be to merge it like it is and missing translations will be updated in a separate PR.

**Comment by KriptoRaptor** [comment]
thank you very much for looking into it. community is getting excited about it
@Patrick1904  let me know if we can do anything about missing parts. discord: KriptoRaptor#5886

**Pull request merged**
