### PR TITLE
Update zh-hans.global.json balance related terms

### PR DESCRIPTION
**Pull request by RubyJiao**
Update zh-hans.global.json balance related terms

### CODE REVIEW

**Comment by MaximusHaximus** [comment]
@RubyJiao :+1: please rebase this on current master and I'll get this shipped this week :)

**Comment by RubyJiao** [comment]
> @RubyJiao 👍 please rebase this on current master and I'll get this shipped this week :)

Hi, I am sorry for my late reply. I do not have write access to rebase. Could you give me the write access?

**Comment by MaximusHaximus** [comment]
@RubyJiao You will need to rebase _in your forked repository_, after syncing your `master` branch in your fork with the current `master` branch in this repo (it should be a fast-forward, see: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)

**Comment by RubyJiao** [comment]
@MaximusHaximus Hi, I pulled 2 new requests instead and I will close this request.

**Pull request closed without merging**
