### PR TITLE
Update Portuguese translation and missing terms

### PR DESCRIPTION
**Pull request by VGasparini**
### Hello :wave: 

This is a PR to update the NEAR Wallet Portuguese translation.

Were an initiative made on Hacktoberfest with supervision and review by guild [NEAR Portuguese](https://www.notion.so/makersnetwork/Comunidade-NEAR-Portugu-s-f385ce229c5444468b9b9c6073e6e5db) 

### Demo
Running locally

image

### Tests
image

### CODE REVIEW

**Comment by he7d3r** [comment]
LGTM

**Comment by MaximusHaximus** [comment]
@esaminu Could you add Portuguese support to the app on this branch and test to be sure switching to it works? Then we can get this merged :)

**Comment by MaximusHaximus** [comment]
@esaminu ref: https://github.com/near/near-wallet/pull/2319

**Comment by esaminu** [comment]
@VGasparini This looks good to go aside from a duplicate key [here](https://github.com/near/near-wallet/blob/f46b414194260171d94564b70dbecc1687e0a27d/packages/frontend/src/translations/pt.global.json#L1562) that's causing the json to be malformed. Should be mergeable after this is removed.

**Comment by VGasparini** [comment]
@esaminu Fixed!

**Comment by MaximusHaximus** [comment]
@VGasparini and the rest of the Portuguese guild -- thanks so much for your contributions, we appreciate the help!

**Pull request merged**
