### PR TITLE
1775 - Add support for multiple ledger transports

### LINKED ISSUE #1775: Implement ledger support for WebHID & WebUSB
**Problem**
Recent updates to Chromium have broken U2F functionality on all Chromium based browsers.  Furthermore, U2F has already been marked as deprecated by Ledger with an intention to remove support for U2F entirely in Q1 2021.

Although Ledger's official migration guide documentation for moving off of the now deprecated U2F transport indicates that we should replace U2F with WebUSB, both U2F and WebUSB have recently been rendered unusable by the latest Chrome v91.xx update.

There is an alternative transport, WebHID, which still works on the latest version of Chromium, however, both WebUSB and WebHID are still in draft stages, and **neither** one is yet supported by Firefox, which _only_ works with the (now deprecated) U2F transport.

Given these facts, and our desire to maintain ledger support for major browsers for as long as we can, we should implement fallback logic that tries each of the available transports and uses whichever one is supported by the current browser.

This pattern has already been introduced in some other open source projects -- an example code pattern that implements fallback for each of the transport types can be found here:
https://github.com/vacuumlabs/adalite/pull/1007/files

We depend on `near-ledger-js` (https://github.com/near/near-ledger-js) for ledger interactions, along with multiple other near ecosystem projects (like `near-cli`, `near-multistaker`), so it would be nice to have this fallback logic in `near-ledger-js` to avoid duplicating it into multiple repositories, especially given how volatile these standards are; we may very well need to implement integration with Ledger Live with the _next_ iteration of changes to Chrome, Firefox, etc.

Reference migration guide **_(obsolete, given Chrome no longer supports WebUSB as of v91.x)_**:
https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md
_"We plan to remove the support of U2F channel proxying on our apps in Q1 2021"_

### PR DESCRIPTION
**Pull request by MaximusHaximus**
Fixes #1775

WiP

## Design
https://www.figma.com/file/TJ8gGKjPfOhnanLH34rzOJ/1834:-Multiple-Ledger-Transports?node-id=370%3A2314

### CODE REVIEW

**Comment by MaximusHaximus** [comment]
@corwinharrell We'll need some design work here, because the new ledger logic will need to be triggered _as a result of a user action_, (e.g. an onClick on a button) and can no longer be done in the background when we render the screen that shows e.g. 'please connect your ledger...' or 'please confirm on your ledger' like we currently do

Also, the new transports are _active_ transports, whereas the old U2F transport was _passive_, meaning the entire negotiation and connection (and failure) would happen at the moment the browser sent the request to the ledger.  With active transports, if someone connects to the ledger, but _then_ they launch the NEAR app, or if they launch the NEAR app, connect to the ledger, then _close the NEAR app_, they will be disconnected from the ledger and need to re-connect (by clicking a button somewhere in the UI!).

See the demo in `near/near-ledger-js`for a barebones example of how I wired this up for a contrived example.  We will need the wallet UI to have basically the same functionality as this demo as far as:
- Presenting a button for the user to initialize a connection to the ledger
- Showing the connection state in the UI
- Updating the connection state in the UI if and when the connection to the ledger is closed
- Allowing the user to re-initialize the connection to the ledger in cases of an error being thrown while attempting to communicate with the ledger -- trying to re-use the same transport after some types of errors have been encountered will _always fail_, so re-connecting with an entirely new transport is the best way to recover from a fatal error communicating with the ledger.

**Comment by vgrichina** [comment]
@MaximusHaximus we generally don't initiate transactions without user clicking on something. Is there any problem with initialising the connection when existing UI actions are performed? Will connection only allow one request per click?

**Comment by MaximusHaximus** [comment]
> @MaximusHaximus we generally don't initiate transactions without user clicking on something. Is there any problem with initialising the connection when existing UI actions are performed? Will connection only allow one request per click?

You can do multiple signings per click, but I believe there is a new behavior to consider vs. U2F (passive), which is that if you open the connection without the NEAR app running, then open the NEAR app _after_ opening the connection, it will be closed 'out from under you', and you will need to create a new connection to actually sign the transaction after you've got the NEAR app running... so you could prompt the user to connect to the ledger... they can click "ok, please do", then when you tell them 'please approve the transaction', they run the NEAR app...it'll drop the connection and force them to re-connect (with a new permission prompt from the browser) before the transaction can be submitted to the ledger for signing.

**Comment by corwinharrell** [comment]
## Design Summary

**Figma Link:** https://www.figma.com/file/TJ8gGKjPfOhnanLH34rzOJ/1834-Multiple-Ledger-Transports?node-id=216%3A193

After navigating to `/sign-in-ledger`, a user must first establish a connection with their device via a button pressed while the device is connected:

Screen Shot 2021-08-19 at 10 33 20 PM

Once the connection has been established, the section state reflects this. They may then click the second button that triggers the existing ledger key addition flow:

Screen Shot 2021-08-19 at 10 33 28 PM

Error states are displayed as modal messages with context sensitive messaging depending on whether the initial connection failed, or if an existing connection was disrupted:

Screen Shot 2021-08-19 at 10 37 50 PM

**Comment by zavodil** [comment]
@vgrichina @stefanopepe 
Is it ready to be merged? I have ongoing questions about chrome&ledger issue from users and developers

**Comment by andy-haynes** [comment]
@MaximusHaximus @heycorwin is this still relevant since fixing Chrome support for ledger? Can we close these out?

**Pull request closed without merging**
