### PR TITLE
Calculate all lockup balances from contract state

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by Patrick1904** [comment]
@vgrichina I've tried to recover my account (that has lockup) but keep getting error about total balance
Screen Shot 2020-12-09 at 6 06 59 PM

**Review by kcole16 — APPROVED** [review]

**Review by frol — APPROVED** [review]
This looks accurate to me

**Comment by mattlockyer** [comment]
1. Went to account with 50 N lockup on mainnet
2. Sent 2 N (had liquid outside lockup) worked
3. Sent 40 N (needed lockup) worked, but now I can't see my account

Assuming glitch with lockup being destroyed, funds sent and remainder going to account? Now no lockup, but there's lingering lockup calc and lookup?

image

**Comment by kcole16** [comment]
@vgrichina Looks like accounts without lockup also triggering an error: https://near-mainnet-staging-wallet-pr-1225.onrender.com/profile/5b4378098c67c414022d65d1d0feb1943e76017acee696a511b5aa960d64e35a

```
Uncaught (in promise) Error: [-32000] Server error: account 7e4c8cf56dda30a6bb00bd3059d429e5cd760876.lockup.near does not exist while viewing
```

**Comment by frol** [comment]
@vgrichina Oh, by the way, will it work correctly when viewing the lockup account itself (instead of the owner of the lockup account)?

**Comment by vgrichina** [comment]
> @vgrichina Looks like accounts without lockup also triggering an error: https://near-mainnet-staging-wallet-pr-1225.onrender.com/profile/5b4378098c67c414022d65d1d0feb1943e76017acee696a511b5aa960d64e35a
> 
> ```
> Uncaught (in promise) Error: [-32000] Server error: account 7e4c8cf56dda30a6bb00bd3059d429e5cd760876.lockup.near does not exist while viewing
> ```

yeah, somehow it worked in my local deploy (usual story from eng lol :D) 

I'm debugging

**Comment by vgrichina** [comment]
> @vgrichina Oh, by the way, will it work correctly when viewing the lockup account itself (instead of the owner of the lockup account)?

it just shows it as regular account:
https://near-mainnet-staging-wallet-pr-1225.onrender.com/profile/5082a3aeb4203818da5a217d53b6365e5cd31b95.lockup.near

**Comment by frol** [comment]
@vgrichina I would find it confusing, especially when the native tokens are delegated from a lockup contract. What is your opinion on it?

**Pull request merged**
