### PR TITLE
Implemented wrap/unwrap Near views

### PR DESCRIPTION
**Pull request by yat011**
issue: https://github.com/near/near-wallet/issues/2256
@Patrick1904 @stefanopepe @corwinharrell

### CODE REVIEW

**Comment by agileurbanite** [comment]
@yat011 we have the new designs would you be open to re-implementing your PR to reflect it? https://www.figma.com/file/Wcl0YlyeasgfBFxJNx7vYS/WAL-48%3A-Wrap%2FUnwrap-NEAR?node-id=2063%3A7314 please let us know by 4/10 latest otherwise we will rebase off of your work and make the necessary adjustments to get this through.  Appreciate your contribution to making a better web wallet experience.

**Comment by agileurbanite** [comment]
Also looks like this PR needs to be rebased and conflicts addressed.

**Comment by andy-haynes** [comment]
@agileurbanite I don't see this referenced by any other PRs so I'm guessing it didn't get rebased. I can take this on as part of my support rotation if it's still a priority. Otherwise let's either get it into the backlog or close out the PR if it's already been addressed as part of someone else's work. I can't see the issue in Jira so not sure whether it's already assigned.

**Comment by agileurbanite** [comment]
@andy-haynes I believe this is live as @judith-Near did this no?

**Comment by andy-haynes** [comment]
> @andy-haynes I believe this is live as @judith-Near did this no?

I'll take your word for it, this PR isn't mentioned by any other PR, Judith isn't mentioned on the GitHub issue, and I don't have access to view the Jira ticket to see progress. I'll close it and we can re-open if there's some disparity with the work that's been done.

**Comment by judith-Near** [comment]
I did not implement the original wrap/unwrap Near functionality (and don't know who did), my ticket was consolidating the swap Near <-> USN with the existing wrap/unwrap Near functionality.

**Pull request closed without merging**
