### PR TITLE
Mainnet Wallet Release 2020-08-26

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by mattlockyer** [comment]
@vgrichina no #844 ?

If you want to produce your own build of the latest multisig master, deploy account and use your hash instead of mine it doesn't matter to me.

All that matters is binary `src/wasm/multisig.wasm` has code_hash included in MULTISIG_CONTRACT_HASHES

**Comment by kcole16** [comment]
Also wondering if we want to include #829

**Comment by vgrichina** [comment]
@kcole16 https://github.com/near/near-wallet/pull/829 ended up taking somewhat more time than I expected, but all ways to setup account should work ok now

**Comment by kcole16** [comment]
@vgrichina Getting `Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE` when using Ledger in this release.

Seems to be working on wallet.testnet.near.org though? I'm testing this release locally, so possibly an issue there?

**Comment by mattlockyer** [comment]
> @vgrichina Getting `Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE` when using Ledger in this release.
> 
> Seems to be working on wallet.testnet.near.org though? I'm testing this release locally, so possibly an issue there?

Always get this locally and even when I run using https.

@Patrick1904 has a trick where you proxy.

**Comment by Patrick1904** [comment]
Minor update: https://github.com/near/near-wallet/pull/852

**Comment by vgrichina** [comment]
> @vgrichina no #844 ?
> 
> If you want to produce your own build of the latest multisig master, deploy account and use your hash instead of mine it doesn't matter to me.
> 
> All that matters is binary `src/wasm/multisig.wasm` has code_hash included in MULTISIG_CONTRACT_HASHES

I just wanna make sure we have a process for deterministic builds, but looks like it's still not established.

**Pull request merged**
