### PR TITLE
2020-11-23 Release

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by Patrick1904** [comment]
@vgrichina would be great to get this one in too: https://github.com/near/near-wallet/pull/1205

Relatively low risk: explaining to users that 2FA staking rewards cannot be calculated ATM.

**Comment by mattlockyer** [comment]
https://github.com/near/near-wallet/pull/1180 works fine as a pre-indexer solution.

There are no "better" solutions to increasing the list of validators we check outside of the current/next set from RPC.

**Comment by mattlockyer** [comment]
Also https://github.com/near/near-wallet/pull/1171 removes has2fa from wallet and instead handles them in TwoFactor class.

This is a step in the direction of abstracting the different account middleware. Not sure if we want to include it yet?

**Comment by mattlockyer** [comment]
This is also super small but I believe fixes those with a "non-refreshed" liquid balance:
https://github.com/near/near-wallet/pull/1203

Confirm with @evgenykuzyakov but according to lockup docs, you should call `refresh_...` before attempting transfers.

**Comment by vgrichina** [comment]
@ihaid any feedback on the release?

**Comment by ihaid** [comment]
> @ihaid any feedback on the release?

@vgrichina I did not find any critical bugs for now, all the findings are in "Issues"

**Review by ihaid — DISMISSED** [review]

**Review by marcinbodnar — DISMISSED** [review]

**Review by Patrick1904 — DISMISSED** [review]

**Review by mattlockyer — DISMISSED** [review]

**Pull request merged**
