### PR TITLE
Release 2020-12-07

### PR DESCRIPTION
**Pull request by vgrichina**
### Release Notes
- New "Send" UI
- Lower minimum balance in the wallet (2 NEAR less!)
- Display function call arguments on the /sign page
- Bug fixes

### CODE REVIEW

**Comment by ihaid** [comment]
Found an issue here when I can't create an account using the seed phrase. Steps:
1. Create a new account using the seed phrase
2. Create one more. Click on "Create new account"
image

3. Choose "Recovery phrase"

4. "Continue" button is disabled 
image

**Comment by Patrick1904** [comment]
> Found an issue here when I can't create an account using the seed phrase. Steps:
> 
> 1. Create a new account using the seed phrase
> 2. Create one more. Click on "Create new account"

@ihaid thank you for catching this! Fix coming today.

**Comment by Patrick1904** [comment]
> Found an issue here when I can't create an account using the seed phrase

@vgrichina I fixed this here: https://github.com/near/near-wallet/pull/1282

**Comment by ihaid** [comment]
There is 2FA confirmation when recovering an account with a seed phrase

**Comment by ihaid** [comment]
sometimes I see this error during send, recovery, or confirmation 
image

**Comment by mattlockyer** [comment]
> sometimes I see this error during send, recovery, or confirmation
@vgrichina typically this is slow network? Large parts of internet experiencing disruption today.

**Comment by ihaid** [comment]
> > sometimes I see this error during send, recovery, or confirmation
> > @vgrichina typically this is slow network? Large parts of internet experiencing disruption today.

I saw it before so I don’t think that it’s connected with today’s outage

**Comment by vgrichina** [comment]
> sometimes I see this error during send, recovery, or confirmation
> image

I think I know how to fix it, we need to change where we get blockNumber from (should use actually finalized block, not optimistic value like right now)

**Comment by vgrichina** [comment]
@ihaid let's give this another round of testing, thanks!

**Comment by ihaid** [comment]
> @ihaid let's give this another round of testing, thanks!

yeah, already started!

**Review by kcole16 — APPROVED** [review]

**Review by ihaid — APPROVED** [review]

**Pull request merged**
